### ISSUE TITLE
Hi Mate! So Can your WebAR-project run for image tracking to render AR effect on that image?THX

### ISSUE THREAD

**Issue by Simon1059770342** [ttak0422/20180512LT_Demo#3]

**Comment by ttak0422** [comment]
Yes!
This project tracks image using ARKit / ARCore.
But it works only with a browser like [WebARonARKit](https://github.com/google-ar/WebARonARKit) / [WebARonARCore](https://github.com/google-ar/WebARonARCore)...

If I start new project like this now, I will use [8th Wall](https://8thwall.com/) 
Because 8th Wall works with normal browser like Chrome.

thx

**Comment by ttak0422** [comment]
Of course WebARonARXXX has charm.
It is unnecessary license and tracking accuracy is preeminent !!

**Comment by Simon1059770342** [comment]
THX! So, is 8th Wall an open-source project just like AR.js that the only thing I should do is to download the file, like AR.js, thress.js etc. and Then coding by myself?

**Comment by ttak0422** [comment]
Sorry for my late correspondence...
8th wall is not an open-source, project but a service.
It is free if you use for local development.
Since it realizes SLAM Engine on the browser, it works even on devices that are not AR Supported.

Why do not you try is?
https://github.com/8thwall/web/tree/master/examples

**Comment by ttak0422** [comment]
WebAR MMD Viewer using 8th wall.
https://github.com/ttak0422/MMDViewer-WebAR-8thWall

**Comment by Simon1059770342** [comment]
THX 4 Ur Help! Except that 8th wall web, are there other open-source for NFT-WebAR you could recommend? THX again!

**Comment by ttak0422** [comment]
I am sorry. I do not know anything except ar.js.
Since Web AR is progressing rapidly, 
I think that it is good to pay attention to [W3C's specifications](https://github.com/immersive-web/webxr).
THX(^^)

**Comment by ttak0422** [comment]
Although it is going to be deprecated, there are things like [this](https://github.com/mozilla/webxr-polyfill).
